/**
 * Amplify Configuration Service
 *
 * This module handles Amplify configuration dynamically.
 * The amplify_outputs.json file is generated by running `npx ampx sandbox`
 * or `npx ampx pipeline-deploy`.
 *
 * Usage in components/composables:
 * ```ts
 * import { configureAmplify, isAmplifyConfigured } from '@/services/amplify'
 *
 * // Call once at app initialization
 * await configureAmplify()
 *
 * // Check if Amplify is ready
 * if (isAmplifyConfigured()) {
 *   // Use Amplify services
 * }
 * ```
 */

import { Amplify } from 'aws-amplify'

let configured = false

/**
 * Configure Amplify with the outputs file
 * Safe to call multiple times - will only configure once
 */
export async function configureAmplify(): Promise<boolean> {
  if (configured) return true

  try {
    // Dynamic import to avoid build errors when file doesn't exist
    const outputs = await import('../../amplify_outputs.json')
    Amplify.configure(outputs.default || outputs)
    configured = true
    console.log('Amplify configured successfully')
    return true
  } catch (error) {
    console.warn(
      'Amplify outputs not found. Backend features will be unavailable.',
      'Run `npx ampx sandbox` to start the local Amplify sandbox.'
    )
    return false
  }
}

/**
 * Check if Amplify has been configured
 */
export function isAmplifyConfigured(): boolean {
  return configured
}

/**
 * Get the Amplify instance (for advanced usage)
 */
export { Amplify }
